const FILENAME_MAP: Record<string, string> = {
  ".gitignore": "Git Config",
  ".gitattributes": "Git Config",
  ".gitmodules": "Git Config",
  Dockerfile: "Docker",
  Containerfile: "Docker",
  "docker-compose.yml": "Docker",
  "docker-compose.yaml": "Docker",
  Makefile: "Makefile",
  GNUmakefile: "Makefile",
  CMakeLists: "CMake",
  Justfile: "Just",
  justfile: "Just",
  ".env": "Env",
  ".env.local": "Env",
  ".env.production": "Env",
  ".env.development": "Env",
  ".env.test": "Env",
  "Cargo.toml": "TOML",
  "Cargo.lock": "TOML",
  "package.json": "JSON",
  "tsconfig.json": "JSON",
  "composer.json": "JSON",
  Gemfile: "Ruby",
  Rakefile: "Ruby",
  Vagrantfile: "Ruby",
  Podfile: "Ruby",
  Brewfile: "Ruby",
  Jenkinsfile: "Groovy",
  "build.gradle": "Groovy",
  "settings.gradle": "Groovy",
  "build.gradle.kts": "Kotlin",
  "settings.gradle.kts": "Kotlin",
  "pom.xml": "XML",
  Procfile: "Shell",
  ".bashrc": "Shell",
  ".zshrc": "Shell",
  ".bash_profile": "Shell",
  ".profile": "Shell",
  ".editorconfig": "EditorConfig",
  ".prettierrc": "JSON",
  ".eslintrc": "JSON",
  "webpack.config.js": "JavaScript",
  "rollup.config.js": "JavaScript",
  "vite.config.ts": "TypeScript",
  "vite.config.js": "JavaScript",
  "next.config.js": "JavaScript",
  "next.config.ts": "TypeScript",
  "nuxt.config.ts": "TypeScript",
  "tailwind.config.js": "JavaScript",
  "tailwind.config.ts": "TypeScript",
  "postcss.config.js": "JavaScript",
};

const EXTENSION_MAP: Record<string, string> = {
  // Top languages
  rs: "Rust",
  py: "Python",
  pyw: "Python",
  pyx: "Python",
  pyi: "Python",
  js: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  ts: "TypeScript",
  mts: "TypeScript",
  cts: "TypeScript",
  tsx: "TypeScript",
  jsx: "JavaScript",
  go: "Go",
  java: "Java",
  kt: "Kotlin",
  kts: "Kotlin",
  rb: "Ruby",
  erb: "Ruby",
  c: "C",
  h: "C",
  cpp: "C++",
  cc: "C++",
  cxx: "C++",
  hpp: "C++",
  hxx: "C++",
  hh: "C++",
  cs: "C#",
  csx: "C#",
  swift: "Swift",
  php: "PHP",
  lua: "Lua",
  zig: "Zig",
  r: "R",
  R: "R",
  rmd: "R",
  dart: "Dart",
  scala: "Scala",
  sc: "Scala",
  ex: "Elixir",
  exs: "Elixir",
  eex: "Elixir",
  heex: "Elixir",
  hs: "Haskell",
  lhs: "Haskell",
  ml: "OCaml",
  mli: "OCaml",
  fs: "F#",
  fsx: "F#",
  fsi: "F#",
  clj: "Clojure",
  cljs: "Clojure",
  cljc: "Clojure",
  edn: "Clojure",
  pl: "Perl",
  pm: "Perl",
  jl: "Julia",
  nim: "Nim",
  v: "V",
  asm: "Assembly",
  s: "Assembly",
  m: "Objective-C",
  mm: "Objective-C",
  groovy: "Groovy",
  pas: "Pascal",
  pp: "Pascal",
  d: "D",
  cr: "Crystal",
  elm: "Elm",
  erl: "Erlang",
  hrl: "Erlang",

  // Frontend frameworks
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",

  // Markup & styles
  html: "HTML",
  htm: "HTML",
  css: "CSS",
  scss: "CSS",
  sass: "CSS",
  less: "CSS",
  styl: "CSS",

  // Data & config
  json: "JSON",
  jsonc: "JSON",
  json5: "JSON",
  yaml: "YAML",
  yml: "YAML",
  toml: "TOML",
  xml: "XML",
  xsl: "XML",
  xslt: "XML",
  svg: "XML",
  ini: "INI",
  cfg: "INI",
  conf: "Conf",
  properties: "Properties",

  // Shell & scripting
  sh: "Shell",
  bash: "Shell",
  zsh: "Shell",
  fish: "Shell",
  ps1: "PowerShell",
  psm1: "PowerShell",
  bat: "Batch",
  cmd: "Batch",

  // Documentation & text
  md: "Markdown",
  markdown: "Markdown",
  mdx: "MDX",
  rst: "reStructuredText",
  tex: "LaTeX",
  txt: "Text",

  // Query & schema
  sql: "SQL",
  graphql: "GraphQL",
  gql: "GraphQL",
  proto: "Protobuf",
  prisma: "Prisma",

  // Infrastructure & DevOps
  tf: "Terraform",
  hcl: "Terraform",
  nix: "Nix",
  dockerfile: "Docker",

  // Other
  vim: "Vim Script",
  el: "Emacs Lisp",
  lisp: "Lisp",
  scm: "Scheme",
  rkt: "Racket",
  wasm: "WebAssembly",
  wat: "WebAssembly",
  sol: "Solidity",
  move: "Move",
  cairo: "Cairo",
};

export function inferLanguage(entity: string): string | undefined {
  const normalized = entity.replace(/\\/g, "/");
  const filename = normalized.split("/").pop() || "";

  if (FILENAME_MAP[filename]) {
    return FILENAME_MAP[filename];
  }

  const dotIdx = filename.lastIndexOf(".");
  if (dotIdx === -1) return undefined;
  const ext = filename.slice(dotIdx + 1).toLowerCase();

  return EXTENSION_MAP[ext];
}
